# -*- coding: utf-8 -*-

<BaseScreen>:
    name: 'base'

    BoxLayout:
        orientation: 'vertical'
        spacing: dp(5)

        ScrollView:
            id: scroll
            size_hint: 1, 1
            do_scroll_x: False

            GridLayout:
                id: grid_card
                cols: 1
                spacing: dp(10)
                padding: dp(10)
                size_hint_y: None
                height: self.minimum_height

                