# -*- coding: utf-8 -*-

<OrderScreen>:
    name: 'order'

    MDTabs:
        id: order_tabs
        tab_display_mode: 'text' 
            
        Tab:
            id: user_order
            text: 'Заявки'

        Tab:
            id: master
            text: "Мастера"

        Tab:
            id: service
            text: 'Услуги'

        Tab:
            id: timetable
            text: 'Время' 
    
    
   